### ISSUE TITLE
TypeError: undefined is not an object in shiny

### ISSUE THREAD

**Issue by NEONKID** [muschellij2/papayaWidget#5]
TypeError: undefined is not an object (evaluating 'results.filter') htmlwidgets.js:475
find htmlwidgets.js:475
a shiny.min.js:3
f shiny.min.js:3
initShiny

Hello.

I want to apply the papaya widget to the shiny app, but I get the above error. 
In my opinion, it seems that you can not find the filter method rather than recognizing the results variable. Is there a solution?

**Comment by NEONKID** [comment]
```R
# Define server logic required to draw a histogram
server <- function(input, output, session) {
    output$papayaView <- renderPapaya({
        papaya(img = as.nifti(imageTensor[1,,]))
    })
}
```

```R
ui <- fluidPage(
    # Application title
    titlePanel("Radiology Demo"),

    # Sidebar with a slider input for number of bins
    sidebarLayout(
        sidebarPanel(
            sliderInput(inputId = "size", label = "Image size", min = 128, max = 256, step = 128, value = 256),
        ),

        # Show a plot of the generated distribution
        mainPanel(
            h3('CT View'),
            papayaOutput(outputId = "papayaView"),
        )
    )
)
```

TypeError: undefined is not an object (evaluating 'results.filter') htmlwidgets.js:475
find htmlwidgets.js:475
a shiny.min.js:3
f shiny.min.js:3
initShiny

Code to read a CT image using a papaya package in a Shiny app. If you compile and run the app after writing this code, the above error will occur.

**Comment by muschellij2** [comment]
What versions of the packages are you using?  See `devtools::session_info()`.  Also please attach the CT image.

**Comment by NEONKID** [comment]
CT image is Kaggle sample DICOM
https://www.kaggle.com/gpreda/visualize-ct-dicom-data/data 

session_info()

package      * version date       source                                   
 abind          1.4-5   2016-07-21 cran (@1.4-5)                            
 assertthat     0.2.0   2017-04-11 cran (@0.2.0)                            
 base64enc      0.1-3   2015-07-28 CRAN (R 3.5.0)                           
 bitops         1.0-6   2013-08-17 CRAN (R 3.5.0)                           
 digest         0.6.16  2018-08-22 CRAN (R 3.5.0)                           
 graphics     * 3.5.0   2018-05-14 local                                    
 grDevices    * 3.5.0   2018-05-14 local                                    
 htmltools      0.3.6   2017-04-28 CRAN (R 3.5.0)                           
 htmlwidgets    1.2     2018-04-19 cran (@1.2)                              
 jsonlite       1.5     2017-06-01 CRAN (R 3.5.0)                           
 matrixStats    0.54.0  2018-07-23 cran (@0.54.0)                           
 methods      * 3.5.0   2018-05-14 local                                    
 neurobase      1.27.1  2018-09-05 Github (neuroconductor/neurobase@0717215)
 oro.nifti      0.9.1   2017-10-26 CRAN (R 3.5.0)                           
 papayaWidget   0.5.4   2018-09-05 Github (muschellij2/papayaWidget@ea501fc)
 R.methodsS3    1.7.1   2016-02-16 cran (@1.7.1)                            
 R.oo           1.22.0  2018-04-22 cran (@1.22.0)                           
 R.utils        2.6.0   2017-11-05 cran (@2.6.0)                            
 Rcpp           0.12.18 2018-07-23 CRAN (R 3.5.0)                           
 RNifti         0.8.1   2018-07-05 cran (@0.8.1)                            
 splines        3.5.0   2018-05-14 local                                    
 stats        * 3.5.0   2018-05-14 local                                    
 tools          3.5.0   2018-05-14 local                                    
 utils        * 3.5.0   2018-05-14 local                                    
 yaml           2.1.19  2018-05-01 cran (@2.1.19)

**Comment by muschellij2** [comment]
Please upload a zip file with the data and create a MCVE: https://stackoverflow.com/help/mcve.  Please upload the full R code.  For example, `imageTensor` is read in somewhere else but does not appear in the `app.R` at all .

**Comment by NEONKID** [comment]
Thank you for your help. This is a problem only on the Ubuntu Linux operating system I use.

I noticed that the Chrome browser on Ubuntu Linux was not recognized properly and prompted me to download the browser again.

**Comment by muschellij2** [comment]
Pleasecreate a MCVE: https://stackoverflow.com/help/mcve.
